Create new version
plinth-tech/config-server pull request #15
Opened 2019-05-15 16:47 UTC by jflora91

create class Configuration & Timestamp(will be used by Configuration and Base class in the future)
createNewVersion method in Service
createNewVersion method in Controller
validation of tenant
creation of version number
logs and exceptions

2019-05-16 10:10 UTC, tsbatista reviewed
Did you properly rebase this PR against the upstream master? You need to ensure you rebase your own work before creating a PR or the history will be nearly impossible to understand. I say this because I was expecting no changes to the gitignore, some changes to the pom (not new files) and a few new java files. I will only do a proper review of this once the PR diff seems a bit healthier.

2019-05-16 10:49 UTC, tsbatista commented on configuration-service/src/main/java/tech/plinth/config/Bootstrap.java
> +@EnableJpaAuditing
What requirement prompted you to enable this?

2019-05-16 10:49 UTC, tsbatista commented on configuration-service/src/main/java/tech/plinth/config/model/Timestamp.java
> +public class Timestamp {
Wait.... What? Why? I really have no idea why you did this! Can you please elaborate on the reasoning behind this file?

2019-05-16 10:49 UTC, tsbatista commented on configuration-service/src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto = create
This can not be here, this setting is dangerous for your data, use flyway instead

2019-05-16 10:49 UTC, tsbatista commented on configuration-service/src/main/resources/application-dev.properties
> +spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
This is not needed, hibernate can auto detect this

2019-05-16 10:49 UTC, tsbatista commented on configuration-service/src/main/resources/application.properties
> +spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect
This can not be here as well, let it be auto detected

2019-05-16 10:49 UTC, tsbatista commented on configuration-service/src/main/java/tech/plinth/config/service/ConfigurationService.java
> +        logger.info("New version of configuration service created: id: {}, version: {}, tenant: {}, data: {}"
What code style is this?

2019-05-16 10:49 UTC, tsbatista commented on configuration-service/src/main/java/tech/plinth/config/service/ConfigurationService.java
> +        List<Configuration> allVersions = configurationRepository.findAll();
This will really really need to change! but lets do it at a later stage!

2019-05-17 09:13 UTC, tsbatista commented
@jflora91 when I ask you to rebase your code I do it with good reason... In this PR you are now attempting to delete three files that were there for good reason and should not be touched by you:
the CODEOWNERS defines the default reviewers, the Jenkinsfile makes the project build on our Jenkins (I will show it to you one day) and the LICENSE is there for legal reasons. Please do not touch any of these files.

2019-05-17 09:17 UTC, jflora91 commented on configuration-service/src/main/java/tech/plinth/config/Bootstrap.java
> +@EnableJpaAuditing
> What requirement prompted you to enable this?

I'm didn't implement auditing in my code, no need this annotation

2019-05-17 09:17 UTC, jflora91 commented on configuration-service/src/main/java/tech/plinth/config/model/Timestamp.java
> +public class Timestamp {
> Wait.... What? Why? I really have no idea why you did this! Can you please elaborate on the reasoning behind this file?

I created this superclass because in the future implementation of Base class i will have the same field created_at and to don't repeat myself i will reuse this class for Base too

2019-05-17 09:17 UTC, jflora91 commented on configuration-service/src/main/java/tech/plinth/config/service/ConfigurationService.java
> +        logger.info("New version of configuration service created: id: {}, version: {}, tenant: {}, data: {}"
> What code style is this?

you are right i refactor that, check if it's ok now

2019-05-17 09:17 UTC, jflora91 commented on configuration-service/src/main/resources/application-dev.properties
> +spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
> This is not needed, hibernate can auto detect this

Solved

2019-05-17 09:17 UTC, jflora91 commented on configuration-service/src/main/resources/application.properties
> +spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect
> This can not be here as well, let it be auto detected

Done

2019-05-17 09:19 UTC, daveseco7 commented on configuration-service/src/main/java/tech/plinth/config/model/Timestamp.java
> +public class Timestamp {
What ? i honestly did not understand the use case

2019-05-17 09:21 UTC, jflora91 commented
> @jflora91 when I ask you to rebase your code I do it with good reason... In this PR you are now attempting to delete three files that were there for good reason and should not be touched by you:
> the CODEOWNERS defines the default reviewers, the Jenkinsfile makes the project build on our Jenkins (I will show it to you one day) and the LICENSE is there for legal reasons. Please do not touch any of these files.

I'm sorry, (i know, i made this mistake again).
For some reason i collect this files to my branch. I will not make this mistake again.

2019-05-17 10:13 UTC, tsbatista commented on configuration-service/src/main/resources/db/migration/V1__create_initial_schema.sql
> +) engine=InnoDB AUTO_INCREMENT=1;
after the `)`, remove everything. As is, this will only run on mysql, meaning it should be in a vendor specific package. As this create table is very simple there is no reason to lock in

2019-05-17 13:37 UTC, jflora91 commented on configuration-service/src/main/resources/db/migration/V1__create_initial_schema.sql
> +) engine=InnoDB AUTO_INCREMENT=1;
> after the `)`, remove everything. As is, this will only run on mysql, meaning it should be in a vendor specific package. As this create table is very simple there is no reason to lock in

I understand your point, it was removed.

2019-05-17 13:48 UTC, tsbatista reviewed
Overall, not it is a lot easier to read... I still need to do a deep review but I do not have the time right now

2019-05-17 13:48 UTC, tsbatista commented on configuration-service/src/main/java/tech/plinth/config/delegate/ConfigurationDelegate.java
> +//        logger.info("The last configuration created as the version: {}", version);
If you want to do this, it is a good place  to log at the debug or trace level

2019-05-17 13:48 UTC, tsbatista commented on configuration-service/src/main/java/tech/plinth/config/delegate/ConfigurationDelegate.java
> +//        logger.info("New version of configuration service created: id: {}, version: {}, tenant: {}, data: {}",
Again, if you want this, then log at a debug level, or completely remove the code

2019-05-17 15:13 UTC, daveseco7 commented on configuration-service/src/main/java/tech/plinth/config/controller/ConfigurationController.java
> +    public JsonNode createNewVersion(@RequestBody JsonNode data_json) {
dataJson

2019-05-17 21:03 UTC, ncarapeto requested changes

2019-05-17 21:03 UTC, ncarapeto commented on configuration-service/src/main/java/tech/plinth/config/service/ConfigurationService.java
> +        if (tenant.isBlank() || tenant.isEmpty()) {
tenant.isBlank() already tests for isEmpty

2019-05-17 21:03 UTC, ncarapeto commented on configuration-service/src/main/java/tech/plinth/config/delegate/ConfigurationDelegate.java
> +        List<Configuration> allVersions = configurationRepository.findByPlatform(platformId);
Are you really going to retrieve the full table from the database? Just to find one specific line? What is the point of database queries? Just imagine you had 1 million records, would you bring them all to memory?

Test something like: 
`Optional<Configuration> findTopByPlatformOrderByVersionDesc(String platformId)`

Plus ideally all should be in a transaction (for concurrency purposes), but we can save that for later.

2019-05-17 21:03 UTC, ncarapeto commented on configuration-service/src/main/resources/db/migration/V1__create_initial_schema.sql
> +    primary key (id));
since we have nothing to prevent concurrency issues, I would add a unique constraint, just to ensure that nobody inserts two lines with the same version at the same time:
`UNIQUE(platform,version)`

2019-05-17 21:03 UTC, ncarapeto commented on pom.xml
> +                <artifactId>flyway-core</artifactId>
already defined in spring-boot-dependencies (with the same version)

2019-05-17 21:03 UTC, ncarapeto commented on pom.xml
> +                <artifactId>mysql-connector-java</artifactId>
not a big deal but this is already defined in spring-boot-dependencies (with a later version even)

2019-05-17 21:03 UTC, ncarapeto commented on configuration-service/src/main/resources/application.properties
> +logging.level.root=DEBUG
Please don't commit the root logging as debug

2019-05-17 21:03 UTC, ncarapeto commented on configuration-service/src/main/java/tech/plinth/config/interceptor/ConfigureRequestContext.java
> +        if (platformId == null || platformId.isBlank() || platformId.isEmpty()) {
replace this line by: `if(Strings.isBlank(platformId)) {`
and by the way, if you test the `platformId.isBlank()` what is the point of testing `platformId.isEmpty()`

2019-05-17 21:03 UTC, ncarapeto commented on configuration-service/src/main/java/tech/plinth/config/database/model/Configuration.java
> +    @NotNull(message = "To create a new version is needed data")
check grammar

2019-05-17 21:03 UTC, ncarapeto commented on configuration-service/src/main/java/tech/plinth/config/database/model/Configuration.java
> +    @GeneratedValue(strategy = GenerationType.AUTO, generator = "native")
I'm curious why you chose GenerationType.AUTO? what happens when you have multiple tables with this?
Google a bit about GenerationType.AUTO vs GenerationType.IDENTITY, the other seems more appropriate.

2019-05-17 21:03 UTC, ncarapeto commented on configuration-service/src/main/resources/db/migration/V1__create_initial_schema.sql
> +    created_at timestamp,
why can this one be null? 
check something like: `creation_date timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP`

2019-05-17 21:03 UTC, ncarapeto commented on configuration-service/src/main/java/tech/plinth/config/database/model/Configuration.java
> +    public void setCreatedAt(OffsetDateTime createdAt) {
To be honest there is no point for this set. IT should be set automatically instead.
anyway, you are not setting the date anywhere...

2019-05-18 10:06 UTC, daveseco7 commented on configuration-service/src/main/java/tech/plinth/config/delegate/ConfigurationDelegate.java
> +        List<Configuration> allVersions = configurationRepository.findByPlatform(platformId);
This is the way to go! If you need help achiving this ping us 😄

2019-05-18 10:08 UTC, daveseco7 commented on configuration-service/src/main/resources/db/migration/V1__create_initial_schema.sql
> +    primary key (id));
I think that PK is always unique, even if you don't explicitly define it as UNIQUE.

2019-05-20 09:12 UTC, jflora91 commented on configuration-service/src/main/java/tech/plinth/config/controller/ConfigurationController.java
> +    public JsonNode createNewVersion(@RequestBody JsonNode data_json) {
> dataJson

Fixed

2019-05-20 09:51 UTC, jflora91 commented on configuration-service/src/main/java/tech/plinth/config/service/ConfigurationService.java
> +        if (tenant.isBlank() || tenant.isEmpty()) {
> tenant.isBlank() already tests for isEmpty

Solved in the new commit

2019-05-20 09:51 UTC, jflora91 commented on configuration-service/src/main/java/tech/plinth/config/delegate/ConfigurationDelegate.java
> +        List<Configuration> allVersions = configurationRepository.findByPlatform(platformId);
> Are you really going to retrieve the full table from the database? Just to find one specific line? What is the point of database queries? Just imagine you had 1 million records, would you bring them all to memory?
> 
> Test something like:
> `Optional<Configuration> findTopByPlatformOrderByVersionDesc(String platformId)`
> 
> Plus ideally all should be in a transaction (for concurrency purposes), but we can save that for later.

Yes, you are right! I made a new implementation taking into account what you said, thank you I think it's much better now

2019-05-20 09:59 UTC, jflora91 commented on configuration-service/src/main/resources/db/migration/V1__create_initial_schema.sql
> +    primary key (id));
> since we have nothing to prevent concurrency issues, I would add a unique constraint, just to ensure that nobody inserts two lines with the same version at the same time:
> `UNIQUE(platform,version)`

I understand your point but if the version is calculated automatically (taking into account the latest version in DB) should we prevent something that not going to happen?

2019-05-20 10:06 UTC, jflora91 commented on pom.xml
> +                <artifactId>flyway-core</artifactId>
> already defined in spring-boot-dependencies (with the same version)

Good point, and should i not redefine the version of mysql-connector-java because is already defined there too?

2019-05-20 10:08 UTC, jflora91 commented on pom.xml
> +                <artifactId>flyway-core</artifactId>
forget, i saw now your comment about that

2019-05-20 10:15 UTC, jflora91 commented on pom.xml
> +                <artifactId>mysql-connector-java</artifactId>
> not a big deal but this is already defined in spring-boot-dependencies (with a later version even)

Done

2019-05-20 10:28 UTC, tsbatista commented on configuration-service/src/main/resources/db/migration/V1__create_initial_schema.sql
> +    primary key (id));
Actually BD constraints are never too much! The if you do not add a constraint and enforce it only in code, you open your database to a problem:
Imagine you are doing maintenance on the service, manually inserting a record on a productive system because... reasons. You make the query to find out the highest version, and as you prepare the query to insert the new version someone invokes the api. You run your insert... and end up with two records containing the same version due to a race condition between you and the running service.

What would happen if the query you run to get ONE instance of the highest version returns two or more records? Try it on your local system and imagine the impact on a productive system!

2019-05-20 14:56 UTC, jflora91 commented on configuration-service/src/main/java/tech/plinth/config/database/model/Configuration.java
> +    @GeneratedValue(strategy = GenerationType.AUTO, generator = "native")
In this case using `GenerationType.AUTO` we can see as a "unique" generator for all tables in the DB (SEQUENCE strategy),  and using `GenerationType.IDENTITY` the id value is set by table.
I have no reason to be using this strategy, just because is the default generation type

2019-05-20 16:09 UTC, jflora91 commented on configuration-service/src/main/resources/db/migration/V1__create_initial_schema.sql
> +    primary key (id));
> Actually BD constraints are never too much! The if you do not add a constraint and enforce it only in code, you open your database to a problem:
> Imagine you are doing maintenance on the service, manually inserting a record on a productive system because... reasons. You make the query to find out the highest version, and as you prepare the query to insert the new version someone invokes the api. You run your insert... and end up with two records containing the same version due to a race condition between you and the running service.
> 
> What would happen if the query you run to get ONE instance of the highest version returns two or more records? Try it on your local system and imagine the impact on a productive system!

completely agree!
I have to protect my service and DB for all eventualities that may occur

2019-05-20 16:13 UTC, jflora91 commented on configuration-service/src/main/resources/application.properties
> +logging.level.root=DEBUG
> Please don't commit the root logging as debug

Switched to `info` level

2019-05-20 16:17 UTC, jflora91 commented on configuration-service/src/main/java/tech/plinth/config/interceptor/ConfigureRequestContext.java
> +        if (platformId == null || platformId.isBlank() || platformId.isEmpty()) {
> replace this line by: `if(Strings.isBlank(platformId)) {`
> and by the way, if you test the `platformId.isBlank()` what is the point of testing `platformId.isEmpty()`

I understand, `isBlank()` check if the string is empty or contains only white space so there is no need to recheck `isEmpty()`

2019-05-20 16:21 UTC, jflora91 commented on configuration-service/src/main/resources/db/migration/V1__create_initial_schema.sql
> +    created_at timestamp,
> why can this one be null?
> check something like: `creation_date timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP`

Can and should be!

2019-05-20 16:30 UTC, jflora91 commented on configuration-service/src/main/java/tech/plinth/config/database/model/Configuration.java
> +    public void setCreatedAt(OffsetDateTime createdAt) {
> To be honest there is no point for this set. IT should be set automatically instead.
> anyway, you are not setting the date anywhere...

I'm setting automatically as you suggest with `default current_timestamp` in sql and i delete this method.

2019-05-21 10:01 UTC, tsbatista commented
@daveseco7 @ncarapeto please review your open comments, if you are happy with the resolutions, lets approve this PR. For now this seem sane enough to create a baseline for further work

2019-05-21 10:02 UTC, tsbatista commented
damn the github UI! that close button without confirmation kills me!

2019-05-21 20:41 UTC, daveseco7 commented on configuration-service/src/main/java/tech/plinth/config/database/repository/ConfigurationRepository.java
> +    Configuration findTopByPlatformOrderByVersionDesc(String platformId);
You added this query, where are you using it ?

2019-05-21 20:42 UTC, daveseco7 commented on configuration-service/src/main/java/tech/plinth/config/delegate/ConfigurationDelegate.java
> +
Did you understand what the new query does ? If you did this delegate would be way different...

2019-05-21 20:47 UTC, daveseco7 commented on configuration-service/src/main/java/tech/plinth/config/database/repository/ConfigurationRepository.java
> +    Configuration findTopByPlatformOrderByVersionDesc(String platformId);
Make this a optional

2019-05-21 20:52 UTC, daveseco7 reviewed
You need to revise your logs. You're pulling too much information which in turn makes the log statments enormous. Log only what you need to debug and understand the problem. Check the logs that are in the request context.

2019-05-21 21:18 UTC, jflora91 commented on configuration-service/src/main/java/tech/plinth/config/delegate/ConfigurationDelegate.java
> +        Configuration lastVersion = configurationRepository.findTopByPlatformOrderByVersionDesc(platformId);
@daveseco7 
From your previous comments, instead of making the query directly in delegate it's better to separate the business logic creating a service that make the query and send the information to delegate, right?

PS: i'm not finding your comments here

2019-05-21 21:21 UTC, daveseco7 commented on configuration-service/src/main/java/tech/plinth/config/delegate/ConfigurationDelegate.java
> +        Configuration lastVersion = configurationRepository.findTopByPlatformOrderByVersionDesc(platformId);
if you're talking about the first comment, i deleted it because i didn't realise you're already using the query 😄

2019-05-21 21:22 UTC, jflora91 commented on configuration-service/src/main/java/tech/plinth/config/delegate/ConfigurationDelegate.java
> +        Configuration lastVersion = configurationRepository.findTopByPlatformOrderByVersionDesc(platformId);
> if you're talking about the first comment, i deleted it because i didn't realise you're already using the query 😄

lol, yes i'm using but now my doubt is if i'm using in the right place

2019-05-21 21:24 UTC, daveseco7 commented on configuration-service/src/main/java/tech/plinth/config/delegate/ConfigurationDelegate.java
> +        Configuration lastVersion = configurationRepository.findTopByPlatformOrderByVersionDesc(platformId);
Come by my place tomorrow and we'll have a coffee and you can explain me why it may or may not make sense to have it there 😄

2019-05-22 15:07 UTC, daveseco7 approved these changes

2019-05-23 10:08 UTC, merged